# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bac42f6b049903581766e94c7170dc96bde49096a1b05589e22cbde774f4f3127347f5bb1074525029f006740f2f5abe6368a1c094cec07fd0eaa4b79ecacf55

test:
  secret_key_base: 907c6caa2a7852fc1fa185a67e18349560d3227ea7a3d12d7fc7f803ff749eb187ea78415b4f2bebf9cfcfce3df263547527fdf72f68409290bc79f3b445e834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
